Replay "elf: Improve diagnostics for static TLS exhaustion"
...also for ia64 to fix build failure:
```
In file included from ../signal/signal.h:316,
                 from ../include/signal.h:2,
                 from ../sysdeps/unix/sysv/linux/sigsetops.h:22,
                 from ../sysdeps/unix/sysv/linux/internal-sigset.h:22,
                 from ../include/stdlib.h:23,
                 from dl-runtime.c:21:
../sysdeps/unix/sysv/linux/ia64/sys/ucontext.h:89:13: warning: variably modified '_pad' at file scope
   89 |             unsigned long _pad[_SC_GR0_OFFSET/8];
      |             ^~~~~~~~
In file included from dynamic-link.h:19,
                 from dl-reloc.c:238:
../sysdeps/ia64/dl-machine.h: In function 'elf_machine_rela':
../sysdeps/ia64/dl-machine.h:398:45: error: macro 'CHECK_STATIC_TLS' requires 3 arguments, but only 2 given
  398 |               CHECK_STATIC_TLS (map, sym_map);
      |                                             ^
In file included from ../sysdeps/ia64/dl-machine.h:30,
                 from dynamic-link.h:19,
                 from dl-reloc.c:30:
./dl-static-tls.h:36:9: note: macro 'CHECK_STATIC_TLS' defined here
   36 | #define CHECK_STATIC_TLS(map, sym_map, sym)                                     \
      |         ^~~~~~~~~~~~~~~~
../sysdeps/ia64/dl-machine.h:398:15: error: 'CHECK_STATIC_TLS' undeclared (first use in this function)
  398 |               CHECK_STATIC_TLS (map, sym_map);
      |               ^~~~~~~~~~~~~~~~
../sysdeps/ia64/dl-machine.h:398:15: note: 'CHECK_STATIC_TLS' is a function-like macro and might be used incorrectly
../sysdeps/ia64/dl-machine.h:398:15: note: each undeclared identifier is reported only once for each function it appears in
```

Fixes: 97f74c6781184a807faa3c0c02f6c5822a98b731 ("elf: Improve diagnostics for static TLS exhaustion")