Revert "math: Remove the SVID error handling from lgammaf/lgammaf_r"
This reverts commit de0e623434fcce907a5be8cc386c95d6b07ba408.

This commit breaks the build for ia64:

```
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251110.040340.118274/glibc-2.42.9000-464-g494ba55d0b/objs/math/libm_pic.a(w_lgamma_compatf.os): in function `__lgammaf_compat':
w_lgamma_compatf.c:(.text+0x0): multiple definition of `__lgammaf_compat'; /usr/src/t2-src/src.glibc.ia64-toolchain.251110.040340.118274/glibc-2.42.9000-464-g494ba55d0b/objs/math/libm_pic.a(w_lgammaf_compat2.os):w_lgammaf_compat2.c:(.text+0x0): first defined here
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251110.040340.118274/glibc-2.42.9000-464-g494ba55d0b/objs/math/libm_pic.a(w_lgammaf.os): in function `__lgammaf':
w_lgammaf.c:(.text+0x22): undefined reference to `__lgammaf_r'
collect2: error: ld returned 1 exit status
make[2]: *** [../Makerules:542: /usr/src/t2-src/src.glibc.ia64-toolchain.251110.040340.118274/glibc-2.42.9000-464-g494ba55d0b/objs/math/libm.so] Error 1
```

...and so far I couldn't find a solution for ia64, so let's revert
it instead for the time being.