Fix build after 1f79bc48382cc204a9cb0eae1d3cca2515af1f3c
After this change the build requires definitions for:

* __truncl, __trunc, __truncf
* __ceill, __ceil, __ceilf

...and fails if not provided:
```
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_fromfpl.os): in function `__fromfpl0':
s_fromfpl.c:(.text+0x72): undefined reference to `__truncl'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_fromfpl.c:(.text+0xa2): undefined reference to `__ceill'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_fromfpxl.os): in function `__fromfpxl0':
s_fromfpxl.c:(.text+0x82): undefined reference to `__truncl'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_fromfpxl.c:(.text+0xb2): undefined reference to `__ceill'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_ufromfpl.os): in function `__ufromfpl0':
s_ufromfpl.c:(.text+0x72): undefined reference to `__truncl'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_ufromfpl.c:(.text+0xa2): undefined reference to `__ceill'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_ufromfpxl.os): in function `__ufromfpxl0':
s_ufromfpxl.c:(.text+0x82): undefined reference to `__truncl'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_ufromfpxl.c:(.text+0xb2): undefined reference to `__ceill'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_fromfp.os): in function `__fromfp0':
s_fromfp.c:(.text+0x62): undefined reference to `__trunc'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_fromfp.c:(.text+0x82): undefined reference to `__ceil'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_fromfpx.os): in function `__fromfpx0':
s_fromfpx.c:(.text+0x72): undefined reference to `__trunc'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_fromfpx.c:(.text+0xa2): undefined reference to `__ceil'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_ufromfp.os): in function `__ufromfp0':
s_ufromfp.c:(.text+0x62): undefined reference to `__trunc'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_ufromfp.c:(.text+0x82): undefined reference to `__ceil'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_ufromfpx.os): in function `__ufromfpx0':
s_ufromfpx.c:(.text+0x72): undefined reference to `__trunc'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_ufromfpx.c:(.text+0xa2): undefined reference to `__ceil'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_fromfpf.os): in function `__fromfpf0':
s_fromfpf.c:(.text+0x62): undefined reference to `__truncf'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_fromfpf.c:(.text+0x82): undefined reference to `__ceilf'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_fromfpxf.os): in function `__fromfpxf0':
s_fromfpxf.c:(.text+0x72): undefined reference to `__truncf'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_fromfpxf.c:(.text+0xa2): undefined reference to `__ceilf'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_ufromfpf.os): in function `__ufromfpf0':
s_ufromfpf.c:(.text+0x62): undefined reference to `__truncf'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_ufromfpf.c:(.text+0x82): undefined reference to `__ceilf'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm_pic.a(s_ufromfpxf.os): in function `__ufromfpxf0':
s_ufromfpxf.c:(.text+0x72): undefined reference to `__truncf'
/usr/src/t2-src/build/ia64-toolchain-24-svn-generic-ia64-itanium2-cross-linux/TOOLCHAIN/cross/bin/../lib/gcc/ia64-t2-linux-gnu/16.0.0/../../../../ia64-t2-linux-gnu/bin/ld: s_ufromfpxf.c:(.text+0xa2): undefined reference to `__ceilf'
collect2: error: ld returned 1 exit status
make[2]: *** [../Makerules:542: /usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/objs/math/libm.so] Error 1
make[2]: Leaving directory '/usr/src/t2-src/src.glibc.ia64-toolchain.251113.035941.118328/glibc-2.42.9000-487-g1f79bc4838/math'
```

So let's provide the missing definitions via the "libm_alias_[...]" macros,
i.e. the ones w/o "_other" at the end. That helps.